name: scratch_card
description: >-
  A customizable scratch card widget for Flutter. Perfect for interactive promotions, games, or hidden reveals.

version: 0.0.3
repository: "https://github.com/devlalin/scratch_card"
tagPattern: ^v{{version}}$


environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
