name: scratch_card
description: "Scartch card for apps"
version: 0.0.1
repository: "https://github.com/devlalin/scratch_card"
tagPattern: ^v{{version}}$

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
